### PR TITLE
qt5: port to Qt5

### PR DESCRIPTION
**Pull request by mathstuf**
---

Not sure of the state of Windows after this.

### CODE REVIEW

**Comment by napcode** [comment]
Thanks for the PR. I'll try to take a look at it in the next days.

**Comment by AnyOldName3** [comment]
This required the following change in order to compile with VS2017:

```diff
@@ -233,11 +233,13 @@ bool ProcessSnapshotModel::Update(void)
 		item->child = new Item(pe, item);
 		item = item->child;
 	}
 
 	::CloseHandle(hSnapshot);
-	this->reset();
+	//this->reset();
+	beginResetModel();
+	endResetModel();
 	return true;
 
 #else /* _WIN32 */
 	// TODO
 	return false;
```

**Comment by mathstuf** [comment]
@AnyOldName3 What was the actual error?

**Comment by AnyOldName3** [comment]
I can't remember the actual error message, but the issue was caused by the `reset()` method being removed in Qt5. I just applied the same fix as was used all over this PR.

**Comment by mathstuf** [comment]
Oh, I see. It's in a Windows-only block of code. No wonder I didn't see it :) .

**Comment by roninbar** [comment]
Hi. How about trying again? It seems that Qt 4 is no longer available for download.

**Comment by napcode** [comment]
Hey, just wanted to let you know that I'm still around. Obviously, I never got around testing and merging this. Sorry but I am open to contributions and even new or additional maintainers. Please let me know if there is any interest.
My own priorities shifted a lot in the recent years and with an employer change back than, GLSL and OpenGL debuggers where no longer in the focus unfortunately.

**Comment by mathstuf** [comment]
Thanks!

**Comment by XenonofArcticus** [comment]
Nice work! I'm glad some folks are still finding this project useful. It's
not in my wheelhouse at the moment, but I am glad to see life in the
project!

**Pull request merged**
